@startuml

Client -> Subject: isPermitted (permission)
Subject -> AuthorizingSecurityManager: isPermitted(getPrincipals(), permission)
AuthorizingSecurityManager -> ModularRealmAuthorizer: isPermitted(PrincipalCollection principals, String permission)
ModularRealmAuthorizer -> AuthorizingRealm: isPermitted(PrincipalCollection principals, String permission)

@enduml