@startuml

interface SecurityManager
interface Realm{
    getAuthenticationInfo(AuthenticationToken token);
}

interface Authenticator{
    authenticate(AuthenticationToken authenticationToken)
}

interface Authorizer{
    boolean isPermitted();
    void checkPermission();
    boolean hasRole();
}

interface AuthenticationInfo{
    getPrincipals()
}

interface CredentialsMatcher{
    boolean doCredentialsMatch(AuthenticationToken token, AuthenticationInfo info)
}

class ModularRealmAuthenticator{
    'Attempts to authenticate the given token by iterating over the internal collection of
    doAuthenticate(AuthenticationToken)
}

class AuthenticatingRealm{
    getAuthenticationInfo(AuthenticationToken token)
}

Authenticator <|-- SecurityManager
SecurityManager <|.. CachingSecurityManager
CachingSecurityManager <|-- RealmSecurityManager
RealmSecurityManager <|-- AuthenticatingSecurityManager
AuthenticatingSecurityManager <|-- AuthorizingSecurityManager
AuthorizingSecurityManager <|-- SessionSecurityManager
SessionSecurityManager <|-- DefaultSecurityManager
DefaultSecurityManager <|-- DefaultWebSecurityManager

Realm <|.. CachingRealm
CachingRealm <|-- AuthenticatingRealm
AuthenticatingRealm <|-- AuthorizaingRealm
AuthorizaingRealm <|-- SimpleAccountRealm
SimpleAccountRealm <|-- IniRealm
IniRealm <-- ModularRealmAuthenticator

Authenticator <|-- AbstractAuthenticator
AbstractAuthenticator <|-- ModularRealmAuthenticator

ModularRealmAuthenticator <-- AuthenticatingSecurityManager

CredentialsMatcher <|.. SimpleCredentialsMatcher

SimpleCredentialsMatcher <- AuthenticatingRealm

@enduml