@startuml

interface SecurityManager
interface Realm{
    getAuthenticationInfo(AuthenticationToken token);
}

interface Authenticator{
    authenticate(AuthenticationToken authenticationToken)
}

interface CredentialsMatcher{
    boolean doCredentialsMatch(AuthenticationToken token, AuthenticationInfo info)
}

interface AuthenticationInfo{
    PrincipalCollection getPrincipals();
    Object getCredentials();
}

class ModularRealmAuthenticator{
    'Attempts to authenticate the given token by iterating over the internal collection of
    doAuthenticate(AuthenticationToken)
}

class AuthenticatingRealm{
    getAuthenticationInfo(AuthenticationToken token)
}

class SimpleAccountRealm{
    doGetAuthenticationInfo(AuthenticationToken token)
}


'--------------------------------SecurityManager----------------------------------
Authenticator <|-- SecurityManager
SecurityManager <|.. CachingSecurityManager
CachingSecurityManager <|-- RealmSecurityManager
RealmSecurityManager <|-- AuthenticatingSecurityManager
AuthenticatingSecurityManager <|-- AuthorizingSecurityManager
AuthorizingSecurityManager <|-- SessionSecurityManager
SessionSecurityManager <|-- DefaultSecurityManager
DefaultSecurityManager <|-- DefaultWebSecurityManager
'--------------------------------SecurityManager----------------------------------


'--------------------------------Realm--------------------------------------------
Realm <|.. CachingRealm
CachingRealm <|-- AuthenticatingRealm
AuthenticatingRealm <|-- AuthorizaingRealm
AuthorizaingRealm <|-- SimpleAccountRealm
SimpleAccountRealm <|-- IniRealm
IniRealm <-- ModularRealmAuthenticator
'--------------------------------Realm---------------------------------------------


'--------------------------------Authenticator--------------------------------------
Authenticator <|-- AbstractAuthenticator
AbstractAuthenticator <|-- ModularRealmAuthenticator
ModularRealmAuthenticator <-- AuthenticatingSecurityManager
'--------------------------------Authenticator---------------------------------------


'--------------------------------CredentialsMatcher----------------------------------
CredentialsMatcher <|.. SimpleCredentialsMatcher
SimpleCredentialsMatcher <- AuthenticatingRealm
'--------------------------------CredentialsMatcher----------------------------------


'--------------------------------AuthenticationInfo----------------------------------
AuthenticationInfo <|-- MergableAuthenticationInfo
AuthenticationInfo <|-- SaltedAuthenticationInfo
MergableAuthenticationInfo <|.. SimpleAuthenticationInfo
SaltedAuthenticationInfo <|.. SimpleAuthenticationInfo

AuthenticationInfo <|-- Account
Account <|.. SimpleAccount
AuthenticationInfo <-- SimpleAccountRealm
'--------------------------------AuthenticationInfo----------------------------------

@enduml