@startuml

interface CredentialsMatcher{
    boolean doCredentialsMatch(AuthenticationToken var1, AuthenticationInfo var2);
}

interface PasswordService{
    String encryptPassword(Object var1) throws IllegalArgumentException;
    boolean passwordsMatch(Object var1, String var2);
}

CredentialsMatcher o-- PasswordService : aggregation



@enduml