@startuml

interface SecurityManager

Authenticator <|-- SecurityManager
Authorizer <|-- SecurityManager
SecurityManager <|.. CachingSecurityManager
CachingSecurityManager <|-- RealmSecurityManager
RealmSecurityManager <|-- AuthenticatingSecurityManager
AuthenticatingSecurityManager <|-- AuthorizingSecurityManager


AuthorizingSecurityManager <|-- SessionSecurityManager
SessionSecurityManager <|-- DefaultSecurityManager
DefaultSecurityManager <|-- DefaultWebSecurityManager
@enduml